In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
import csv
import requests
from scipy import stats
headers = { 
    'accept': "application/json", 
    'apikey': "8a6c3ab67caa3a66c274d4455dc0ebc3" }

C:\Anaconda3\envs\PythonData\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

In [40]:
cities_df = pd.read_csv("./resources/ListOfCities.csv")
cities_df.head()

         State           City
0        Texas         Dallas
1   California  San Francisco
2  Mississippi        Jackson

In [10]:
base_url ="https://search.onboard-apis.com/areaapi/v2.0.0/state/lookup"
res = requests.get(base_url,headers=headers).json()
res
st_data =pd.DataFrame(res['response']['result']['package']['item'])
st_data.rename(columns={'name':'State','geo_key':'St_geo_key'}, inplace=True)
statedata = st_data[['State','St_geo_key','abbreviation']]
statedata.head()

        State St_geo_key abbreviation
0     Alabama       ST01           AL
1      Alaska       ST02           AK
2     Arizona       ST04           AZ
3    Arkansas       ST05           AR
4  California       ST06           CA

In [11]:
city_table =pd.merge(cities_df, statedata, on="State", how="left")
city_table.head()

         State           City St_geo_key abbreviation
0        Texas         Dallas       ST48           TX
1   California  San Francisco       ST06           CA
2  Mississippi        Jackson       ST28           MS

In [12]:
appended_new = pd.DataFrame([])
for index, row in city_table.iterrows():
    stgc = row['St_geo_key']
    city = row['City']  
    state = row['State']
    state_abbre = row['abbreviation']
    city_url ="https://search.onboard-apis.com/areaapi/v2.0.0/county/lookup/?StateId="+stgc+"&GeoType=CO" 
    
    resc = requests.get(city_url,headers=headers).json()
    city_data = pd.DataFrame(resc['response']['result']['package']['item'])
    new = city_data.loc[city_data['name'] == city]
    new['state'] = state
    new['state abbreviation'] = state_abbre
    appended_new = appended_new.append(new)
    
appended_new

C:\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

,geo_center_latitude,geo_center_longitude,geo_key,id,name,type,state,state abbreviation
56,32.7669870000,-96.7784240000,CO48113,CO48113,Dallas,CO,Texas,TX
37,37.7272390000,-123.0322290000,CO06075,CO06075,San Francisco,CO,California,CA
29,30.4560050000,-88.6251010000,CO28059,CO28059,Jackson,CO,Mississippi,MS

In [15]:
# pull airx, ozone, pm10, rskcyhanx, rskcyhunx, rskcyquak, rskcyrisk data at city level

appended_environ = pd.DataFrame([])

for index, row in appended_new.iterrows():
    geok = row['geo_key']
    county_city = row['name']
    state = row['state']
    state_abbre = row['state abbreviation']
    
    print(geok)
  
    base_url="https://search.onboard-apis.com/communityapi/v2.0.0/area/full?AreaId="+geok
    try:
        response = requests.get(base_url,headers=headers)
        if response.status_code == requests.codes.ok:
            rescity = response.json()
            city_toadd = pd.DataFrame(rescity['response']['result']['package']['item'])
            city_toadd['county name']=county_city
            city_toadd['state'] = state
            city_toadd['state abbreviation'] = state_abbre
            city_toadd['county_geo_key'] = geok
            appended_environ = appended_environ.append(city_toadd)
        else:
            print("city data not found. Skipping...")
    except:         
        print("Unknown exception...")
        pass
        
appended_environ.head()

CO48113
CO06075
CO28059

,age00_04,age05_09,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,...,trwpublic,trwself,two_bed_county,two_bedindex,vph1,vphgt1,vphnone,county name,state abbreviation,county_geo_key
0,214678,200169,184725,190163,164684,169380,191962,191305,181247,168042,...,36957,17420,1031,98,40,53,7,Dallas,TX,CO48113
0,73814,41771,34495,29645,38407,52461,80598,81804,72933,64653,...,130734,39328,3018,100,41,27,32,San Francisco,CA,CO06075
0,8960,9263,9566,10500,9479,8793,8645,8928,9039,9239,...,219,508,789,95,32,64,4,Jackson,MS,CO28059

In [22]:
# airx	A score that represents the relative air quality by combining indices of Ozone, Carbon Monoxide, Lead, Nitrogen Oxide, and Particulate matter and comparing to the national average of 100. A score of 200 indicates twice the presence of air pollutants than the national average, while 50 indicates half the presence. The different types of pollution are given equal weight in this score.	
# ozone	An invisible gas that irritates and impairs breathing. Index score (100=National Average).
#  pm10	Fine particles of pollutants which tend to reduce visibility and invade the lungs deeply. Index score (100=National Average)
# rskcyhanx	The total risk of damaging hailstorms. Based on analysis of historical hail frequency and severity. Index score (100=National Average)
# rskcyhunx	The total hurricane risk. Based on analysis of historical hurricane tracks and intensity. Index score (100=National Average)
# rskcyquak	The total earthquake risk. Based on analysis of historical earthquake magnitudes and fault locations. Index score (100=National Average)
# rskcyrisk	The total risk from various storm types (hurricanes, tornadoes, damaging hailstorms and damaging wind storms). Index score (100=National Average)

raw_environ_df = appended_environ[['county_geo_key','county name','state','state abbreviation',\
                                   'airx','ozone','pm10','rskcyhanx',\
                                   'rskcyhunx','rskcyquak','rskcyrisk']]
raw_environ_df

,county_geo_key,county name,state,state abbreviation,airx,ozone,pm10,rskcyhanx,rskcyhunx,rskcyquak,rskcyrisk
0,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,217
0,CO06075,San Francisco,California,CA,87,101,102,0,0,456,2
0,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,248

In [17]:
appended_zip = pd.DataFrame([])
for index, row in appended_new.iterrows():
    geoid = row['geo_key']
    city = row['name']
    state = row['state']
    state_abbre = row['state abbreviation']
    zip_url ="https://search.onboard-apis.com/areaapi/v2.0.0/geoid/lookup/?geoId="+geoid+"&GeoType=ZI" 
    
    resc_zip = requests.get(zip_url,headers=headers).json()
    city_data = pd.DataFrame(resc_zip['response']['result']['package']['item'])
    city_data['county name']=city
    city_data['state'] = state
    city_data['state abbreviation'] = state_abbre
    appended_zip = appended_zip.append(city_data)
    
appended_zip.head()

,area,area_unit,geo_key,id,name,type,county name,state,state abbreviation
0,0.0052,sq. mi.,ZI75390,75390,Dallas,ZI,Dallas,Texas,TX
1,0.0057,sq. mi.,ZI75270,75270,Dallas,ZI,Dallas,Texas,TX
2,0.4437,sq. mi.,ZI75251,75251,Dallas,ZI,Dallas,Texas,TX
3,0.4525,sq. mi.,ZI75246,75246,Dallas,ZI,Dallas,Texas,TX
4,0.7034,sq. mi.,ZI75202,75202,Dallas,ZI,Dallas,Texas,TX

In [18]:
appended_main = pd.DataFrame([])

for index, row in appended_zip.iterrows():
    cgc = row['geo_key']
    city = row['name']
    county_city = row['county name']
    state = row['state']
    state_abbre = row['state abbreviation']
    
    print(cgc)
  
    base_url="https://search.onboard-apis.com/communityapi/v2.0.0/area/full?AreaId="+cgc
    try:
        response = requests.get(base_url,headers=headers)
        if response.status_code == requests.codes.ok:
            resct = response.json()
            zip_toadd = pd.DataFrame(resct['response']['result']['package']['item'])
            zip_toadd['name']=city
            zip_toadd['county name']=county_city
            zip_toadd['state'] = state
            zip_toadd['state abbreviation'] = state_abbre
            zip_toadd['geo_key'] = cgc
            appended_main = appended_main.append(zip_toadd)
        else:
            print("zip data not found. Skipping...")
    except:         
        print("Unknown exception...")
        pass
        
appended_main.head()

ZI75390
ZI75270
zip data not found. Skipping...
ZI75251
ZI75246
ZI75202
ZI75226
ZI75201
ZI75219
ZI75210
ZI75204
ZI75254
ZI75223
ZI75233
ZI76155
ZI75209
ZI75240
ZI75001
ZI75207
ZI75206
ZI75205
ZI75244
ZI75249
ZI75225
ZI75203
ZI75252
ZI75116
ZI75039
ZI75287
ZI75231
ZI75224
ZI75208
ZI75137
ZI75054
ZI75247
ZI75238
ZI75237
ZI75235
ZI75218
ZI75230
ZI75248
ZI75042
ZI75214
ZI75180
ZI75082
ZI75041
ZI75232
ZI75215
ZI75243
ZI75081
ZI75134
ZI75212
ZI75048
ZI75234
ZI75044
ZI75062
ZI75227
ZI75228
ZI75080
ZI75089
ZI75061
ZI75220
ZI75172
ZI75007
ZI75088
ZI75141
ZI75229
ZI75150
ZI75236
ZI75067
ZI75038
ZI75060
ZI75253
ZI75051
ZI75216
ZI75063
ZI75040
ZI75149
ZI75006
ZI75181
ZI75019
ZI75211
ZI75043
ZI75182
ZI75115
ZI75050
ZI75241
ZI75052
ZI75217
ZI75146
ZI75104
ZI75098
ZI76051
ZI75154
ZI75159
ZI75125
ZI94104
ZI94108
ZI94105
ZI94111
ZI94102
ZI94130
ZI94133
ZI94123
ZI94115
ZI94158
ZI94109
ZI94103
ZI94114
ZI94117
ZI94127
ZI94107
ZI94118
ZI94131
ZI94129
ZI94110
ZI94122
ZI94134
ZI94116
ZI94121
ZI94112
ZI94132
ZI94124
ZI39567
ZI39581
ZI39563
ZI39553
ZI39564
ZI39532
ZI39562
ZI39565
ZI39573
ZI39452

,age00_04,age05_09,age10_14,age15_19,age20_24,age25_29,age30_34,age35_39,age40_44,age45_49,...,trwother,trwpublic,trwself,two_bed_county,two_bedindex,vph1,vphgt1,vphnone,county name,state abbreviation
0,1,1,0,1,3,3,3,2,2,2,...,0,0,0,1031,0,55,37,8,Dallas,TX
0,376,114,88,23,40,269,463,318,164,101,...,5,8,24,1031,129,40,36,23,Dallas,TX
0,260,187,156,135,147,219,279,280,223,173,...,17,106,32,1031,81,52,33,15,Dallas,TX
0,426,102,76,22,47,239,557,470,283,200,...,13,32,224,1031,136,55,37,9,Dallas,TX
0,447,259,192,129,200,438,552,456,367,306,...,5,170,145,1031,103,62,31,7,Dallas,TX

In [26]:
# geo_key	Full geographic identifier used for searching.
# latitude	Centroid latitude for the area.    
# longitude	Centroid longitude for the area.	
# airportdist	Distance to closest airport with more than 10,000 boardings annually. Calculated from the geographic centroid of the Census Zip Area (CZA).
# ancestamer	Number of people living within the area of American descent.
# ancestamind	Number of people living within the area of Native American descent.
# ancestasian	Number of people living within the area of Asian descent.
# ancesteuro	Number of people living within the area of European descent.
# ancesthawai	Number of people living within the area of Hawaiian descent.
# ancesthisp	Number of people living within the area of Hispanic descent.
# ancestother	Number of people living within the area of a descent listed as Other.
# ancestunclassified	Number of people living within the area of an unclassified descent.
# avgsaleprice	Average property tax amount for the area.
# avg_prop_tax_year_count	Average residential home sales price for four recent quarters. Based on actual sales collected from Assessor's offices. All included sales are arms length transactions greater than $25,000 representing single family and multi-family (2 - 4) residential sales.  * Note: This field is only available for approximately 2,500 counties nationally.
# cocrmcytotc	Only included for ZI, PL, CS and TR level records: A score that represents the combined risks of rape, murder, assault, robbery, burglary, larceny and vehicle theft compared to the national average of 100. A score of 200 indicates twice the national average total crime risk, while 50 indicates half the national risk. The different types of crime are given equal weight in this score.
# crmcytotc	A score that represents the combined risks of rape, murder, assault, robbery, burglary, larceny and vehicle theft compared to the national average of 100. A score of 200 indicates twice the national average total crime risk, while 50 indicates half the national risk. The different types of crime are given equal weight in this score.
# daypop	The daytime population in this area.
# edubach	Number of people who achieved a Bachelor's Degree.
# eduagelt9_00	Education attainment from Census 2000: Number of people who achieved an 8th grade education.
# eduhsch	Number of people who are high school graduates.
# expfoodbev	The costs associated with food at home, food away from home; restaurants, catered affairs, non-alcoholic and alcoholic beverages. Index score (100=National Average)
# exphealth	The costs associated with health care including: health insurance, medicare payments, medical services, prescription and non prescription drugs and medical supplies. Index score (100=National Average)
# exphh	The costs associated with owned dwellings; maintenance, repairs, homeowners insurance, property management and security. Index score (100=National Average)
# exphhops	The costs associated with household operations; in home babysitting and child care, day care, nursery and preschools. Also includes other household expenses like: housekeeping services and supplies, lawn care services, home security, pest control, appliance repair and rental as well as other household products and postage. Index score (100=National Average)
# exptotal	Average annual expenditures for food, beverages, housing, utilities, household operations, household supplies and furnishings, apparel, transportation, health care, entertainment, personal care, personal insurance, education and miscellaneous. (100=National Average)
# exptransport	The costs associated with new and used vehicle purchases, vehicle finance charges, gasoline and oil, vehicle repair and maintenance, vehicle insurance, parking and tolls, public transportation and other transportation costs. Index score (100=National Average)
# three_bedindex	Localized index to show expected local pricing variations for a three bedroom dwelling.
# three_bed_county	Gross rent estimate for a three bedroom apartment; includes the shelter rent plus the cost of all tenant-paid utilities, except telephones, cable or satellite television service, and internet service.
# idxexptotal	The average of the total expenses shown within an area per household as it relates to the national average. Index score (100=National Average)
# inccypcap	Average individual income of people in the area.
# inccyavehh	Average income of households in the area.
# medsaleprice	Median residential home sales price for four recent quarters. Based on actual sales collected from Assessor's offices. All included sales are arms length transactions greater than $25,000 representing single family and multi-family (2 - 4) residential sales. Note: This field is only available for approximately 2,500 counties nationally.
# precipann	Combined average annual rainfall and snowfall in inches.
# salestaxrate	The reported sales tax rate for the area. Additional local taxes may apply (see SALESTAXTYPE).
# trwave	The average commute time of workers living in this area.


appended_zip = appended_main[['geo_key','name','county name','state','state abbreviation',\
                            'longitude','latitude',\
                            'airportdist','ancestamer',\
                            'ancestamind','ancestasian','ancesteuro',\
                            'ancesthawai','ancesthisp','ancestother',\
                            'ancestunclassified','avgsaleprice',\
                           'avg_prop_tax_year_count','cocrmcytotc',\
                           'crmcytotc','daypop','edubach','eduagelt9_00',\
                           'eduhsch','expfoodbev','exphealth',\
                           'exphh','exphhops','exptotal','exptransport',\
                           'three_bedindex','three_bed_county','idxexptotal',\
                           'inccypcap','inccyavehh','medsaleprice',\
                           'precipann','salestaxrate',\
                           'trwave']]
appended_zip

,geo_key,name,county name,state,state abbreviation,longitude,latitude,airportdist,ancestamer,ancestamind,...,exptransport,three_bedindex,three_bed_county,idxexptotal,inccypcap,inccyavehh,medsaleprice,precipann,salestaxrate,trwave
0,ZI75390,Dallas,Dallas,Texas,TX,-96.840650,32.814164,2,0,0,...,132,0,1390,125,116104,64827,,37.05,6.25,53
0,ZI75251,Dallas,Dallas,Texas,TX,-96.771521,32.917204,7,110,8,...,59,129,1390,55,49316,78448,221151,40.39,6.25,16
0,ZI75246,Dallas,Dallas,Texas,TX,-96.770643,32.795407,6,27,14,...,85,81,1390,81,32462,72713,267187,37.05,6.25,30
0,ZI75202,Dallas,Dallas,Texas,TX,-96.803858,32.781909,5,99,17,...,60,136,1390,56,74201,107188,201250,37.05,6.25,19
0,ZI75226,Dallas,Dallas,Texas,TX,-96.774934,32.786490,6,65,20,...,86,103,1390,79,37050,69986,142500,37.05,6.25,28
0,ZI75201,Dallas,Dallas,Texas,TX,-96.801727,32.788921,5,407,88,...,59,159,1390,55,91175,139473,505875,37.05,6.25,16
0,ZI75219,Dallas,Dallas,Texas,TX,-96.813994,32.811967,3,466,109,...,74,112,1390,70,62712,112875,268850,37.05,6.25,19
0,ZI75210,Dallas,Dallas,Texas,TX,-96.742837,32.768991,8,80,9,...,86,66,1390,85,10118,27787,38265,37.05,6.25,32
0,ZI75204,Dallas,Dallas,Texas,TX,-96.790236,32.803217,5,1161,132,...,67,128,1390,63,59171,103629,352837,37.05,6.25,21
0,ZI75254,Dallas,Dallas,Texas,TX,-96.807231,32.943798,7,450,80,...,74,94,1390,70,35347,72689,157500,40.39,6.25,22
0,ZI75223,Dallas,Dallas,Texas,TX,-96.747905,32.793831,7,76,47,...,116,81,1390,111,18052,59358,267734,37.05,6.25,31
0,ZI75233,Dallas,Dallas,Texas,TX,-96.872497,32.706895,10,174,33,...,109,78,1390,104,15815,49486,141015,37.92,6.25,31
0,ZI76155,Fort Worth,Dallas,Texas,TX,-97.052633,32.822535,5,185,18,...,53,100,1338,52,36421,59561,,34.73,6.25,19
0,ZI75209,Dallas,Dallas,Texas,TX,-96.825709,32.846125,1,569,39,...,90,135,1390,87,70107,151713,521250,37.05,6.25,20
0,ZI75240,Dallas,Dallas,Texas,TX,-96.779295,32.933227,7,324,60,...,96,93,1390,91,25715,68465,250000,40.39,6.25,23
0,ZI75001,Addison,Dallas,Texas,TX,-96.842184,32.952099,7,458,49,...,66,112,1390,62,43105,77504,299100,38.02,6.25,22
0,ZI75207,Dallas,Dallas,Texas,TX,-96.818735,32.781106,5,239,22,...,132,152,1390,124,28557,64832,650000,37.05,6.25,53
0,ZI75206,Dallas,Dallas,Texas,TX,-96.769446,32.833127,5,1076,169,...,65,114,1390,62,44220,79841,400000,37.05,6.25,23
0,ZI75205,Highland Park,Dallas,Texas,TX,-96.794717,32.837134,3,1582,68,...,109,158,1390,105,88440,219232,900000,37.05,6.25,16
0,ZI75244,Farmers Branch,Dallas,Texas,TX,-96.838805,32.921951,5,532,65,...,94,124,1390,91,46494,107202,425000,37.05,6.25,21
0,ZI75249,Dallas,Dallas,Texas,TX,-96.957236,32.642795,15,167,43,...,115,112,1390,108,20543,63613,143796,37.92,6.25,32
0,ZI75225,Dallas,Dallas,Texas,TX,-96.791251,32.862278,4,1442,42,...,109,176,1390,107,101251,237498,875000,37.05,6.25,18
0,ZI75203,Dallas,Dallas,Texas,TX,-96.808826,32.747705,7,170,57,...,96,78,1390,92,14726,41601,82310,37.05,6.25,32
0,ZI75252,Dallas,Dallas,Texas,TX,-96.789978,32.997247,11,817,70,...,81,80,1390,78,47151,94255,335500,40.39,6.25,23
0,ZI75116,Duncanville,Dallas,Texas,TX,-96.911374,32.658893,14,888,57,...,111,87,1390,105,20398,60129,121056,37.92,6.25,26
0,ZI75039,Irving,Dallas,Texas,TX,-96.940717,32.888701,5,306,62,...,69,130,1390,65,76356,132934,407373,34.73,6.25,19
0,ZI75287,Dallas,Dallas,Texas,TX,-96.844056,33.000899,11,1668,187,...,78,76,1390,73,40121,77269,258313,38.02,6.25,25
0,ZI75231,Dallas,Dallas,Texas,TX,-96.749679,32.874034,6,690,113,...,90,81,1390,86,28168,70389,319092,37.05,6.25,28
0,ZI75224,Dallas,Dallas,Texas,TX,-96.838349,32.711524,9,241,107,...,116,79,1390,111,13822,45911,135094,37.33,6.25,28
0,ZI75208,Dallas,Dallas,Texas,TX,-96.840416,32.747098,7,280,123,...,115,84,1390,110,25368,78128,332500,37.05,6.25,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,ZI94123,San Francisco,San Francisco,California,CA,-122.436581,37.800287,13,557,20,...,89,121,3927,88,100902,169061,2200000,22.28,8.50,28
0,ZI94115,San Francisco,San Francisco,California,CA,-122.436388,37.785245,12,478,50,...,94,102,3927,92,72564,135147,1375000,22.28,8.50,27
0,ZI94158,San Francisco,San Francisco,California,CA,-122.392339,37.771999,11,137,19,...,95,146,3927,91,77960,145748,1301000,22.28,8.50,17
0,ZI94109,San Francisco,San Francisco,California,CA,-122.420045,37.790945,12,900,184,...,81,96,3927,79,63948,105357,1050000,22.28,8.50,26
0,ZI94103,San Francisco,San Francisco,California,CA,-122.413890,37.774183,11,525,286,...,96,70,3927,93,56088,106080,775000,22.28,8.50,26
0,ZI94114,San Francisco,San Francisco,California,CA,-122.434801,37.758285,10,705,70,...,104,119,3927,101,87059,165628,1550000,22.28,8.50,28
0,ZI94117,San Francisco,San Francisco,California,CA,-122.442931,37.771142,11,669,105,...,109,111,3927,105,65274,137154,1325000,22.28,8.50,28
0,ZI94127,San Francisco,San Francisco,California,CA,-122.458131,37.735657,9,265,30,...,144,123,3927,142,67464,170242,1450000,22.28,8.50,28
0,ZI94107,San Francisco,San Francisco,California,CA,-122.396218,37.770246,11,376,78,...,99,126,3927,96,85198,157733,1150000,22.28,8.50,24
0,ZI94118,San Francisco,San Francisco,California,CA,-122.462013,37.781244,12,467,52,...,116,107,3927,114,63662,139512,1550000,22.28,8.50,29
0,ZI94131,San Francisco,San Francisco,California,CA,-122.439146,37.743833,9,541,57,...,111,117,3927,109,65509,137434,1278870,22.28,8.50,29
0,ZI94129,San Francisco,San Francisco,California,CA,-122.466310,37.796306,13,71,8,...,159,174,3927,152,74870,220426,,22.28,8.50,28
0,ZI94110,San Francisco,San Francisco,California,CA,-122.416232,37.751127,10,658,197,...,128,98,3927,125,49666,124329,1250000,22.28,8.50,28
0,ZI94122,San Francisco,San Francisco,California,CA,-122.484724,37.759278,12,451,76,...,128,108,3927,125,44531,111720,1103000,19.77,8.50,33
0,ZI94134,San Francisco,San Francisco,California,CA,-122.410616,37.719053,7,124,65,...,172,80,3927,169,22507,81007,706000,22.28,8.50,33
0,ZI94116,San Francisco,San Francisco,California,CA,-122.487495,37.744079,11,304,61,...,145,107,3927,142,45800,128690,1086500,19.77,8.50,34
0,ZI94121,San Francisco,San Francisco,California,CA,-122.490754,37.778607,13,348,76,...,118,100,3927,116,47973,112912,1225000,19.77,8.50,33
0,ZI94112,San Francisco,San Francisco,California,CA,-122.442258,37.719722,8,235,137,...,177,96,3927,172,26136,93433,820000,22.28,8.50,31
0,ZI94132,San Francisco,San Francisco,California,CA,-122.477150,37.720765,9,155,80,...,130,112,3927,127,32190,88029,1012500,19.77,8.50,32
0,ZI94124,San Francisco,San Francisco,California,CA,-122.390993,37.729810,8,287,125,...,162,69,3927,158,21860,75279,640000,22.28,8.50,30
0,ZI39567,Pascagoula,Jackson,Mississippi,MS,-88.543480,30.361710,29,1089,47,...,84,83,1149,86,23367,59147,,67.01,7.00,17
0,ZI39581,Pascagoula,Jackson,Mississippi,MS,-88.520239,30.366757,28,803,24,...,86,89,1149,88,20164,53539,,67.01,7.00,19
0,ZI39563,Moss Point,Jackson,Mississippi,MS,-88.527821,30.407154,26,977,27,...,82,83,1149,85,19612,50045,,67.01,7.00,22
0,ZI39553,Gautier,Jackson,Mississippi,MS,-88.644169,30.406278,25,1495,86,...,89,91,1149,90,22723,60201,,72.10,7.00,23
0,ZI39564,Ocean Springs,Jackson,Mississippi,MS,-88.777524,30.405013,17,3681,147,...,93,117,1149,94,30237,79328,,72.10,7.00,22
0,ZI39532,Biloxi,Jackson,Mississippi,MS,-88.931057,30.461212,9,3774,150,...,89,105,1066,90,25003,64836,162625,64.84,7.00,23
0,ZI39562,Escatawpa,Jackson,Mississippi,MS,-88.507256,30.553407,19,4060,58,...,93,72,1149,94,23267,63758,,72.10,7.00,29
0,ZI39565,Vancleave,Jackson,Mississippi,MS,-88.756709,30.532106,20,3429,107,...,99,90,1149,100,24237,69057,,72.10,7.00,30
0,ZI39573,Perkinston,Jackson,Mississippi,MS,-89.178315,30.721326,23,1595,42,...,94,85,918,96,20264,55137,47500,64.46,7.00,36
0,ZI39452,Lucedale,Jackson,Mississippi,MS,-88.576738,30.868730,24,5815,95,...,95,77,995,95,20786,57931,92000,65.69,7.00,37

In [31]:
raw_all_df = raw_environ_df.merge(appended_zip, left_on='county name', right_on='county name')
raw_all_df.head()

,county_geo_key,county name,state_x,state abbreviation_x,airx,ozone,pm10,rskcyhanx,rskcyhunx,rskcyquak,...,exptransport,three_bedindex,three_bed_county,idxexptotal,inccypcap,inccyavehh,medsaleprice,precipann,salestaxrate,trwave
0,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,132,0,1390,125,116104,64827,,37.05,6.25,53
1,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,59,129,1390,55,49316,78448,221151,40.39,6.25,16
2,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,85,81,1390,81,32462,72713,267187,37.05,6.25,30
3,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,60,136,1390,56,74201,107188,201250,37.05,6.25,19
4,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,86,103,1390,79,37050,69986,142500,37.05,6.25,28

In [32]:
raw_all_df.shape

(131, 49)

In [35]:
raw_all_df1 = raw_all_df.reset_index()
raw_all_reset = raw_all_df1.drop(columns=['index'])

raw_all_reset

,county_geo_key,county name,state_x,state abbreviation_x,airx,ozone,pm10,rskcyhanx,rskcyhunx,rskcyquak,...,exptransport,three_bedindex,three_bed_county,idxexptotal,inccypcap,inccyavehh,medsaleprice,precipann,salestaxrate,trwave
0,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,132,0,1390,125,116104,64827,,37.05,6.25,53
1,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,59,129,1390,55,49316,78448,221151,40.39,6.25,16
2,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,85,81,1390,81,32462,72713,267187,37.05,6.25,30
3,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,60,136,1390,56,74201,107188,201250,37.05,6.25,19
4,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,86,103,1390,79,37050,69986,142500,37.05,6.25,28
5,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,59,159,1390,55,91175,139473,505875,37.05,6.25,16
6,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,74,112,1390,70,62712,112875,268850,37.05,6.25,19
7,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,86,66,1390,85,10118,27787,38265,37.05,6.25,32
8,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,67,128,1390,63,59171,103629,352837,37.05,6.25,21
9,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,74,94,1390,70,35347,72689,157500,40.39,6.25,22
10,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,116,81,1390,111,18052,59358,267734,37.05,6.25,31
11,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,109,78,1390,104,15815,49486,141015,37.92,6.25,31
12,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,53,100,1338,52,36421,59561,,34.73,6.25,19
13,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,90,135,1390,87,70107,151713,521250,37.05,6.25,20
14,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,96,93,1390,91,25715,68465,250000,40.39,6.25,23
15,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,66,112,1390,62,43105,77504,299100,38.02,6.25,22
16,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,132,152,1390,124,28557,64832,650000,37.05,6.25,53
17,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,65,114,1390,62,44220,79841,400000,37.05,6.25,23
18,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,109,158,1390,105,88440,219232,900000,37.05,6.25,16
19,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,94,124,1390,91,46494,107202,425000,37.05,6.25,21
20,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,115,112,1390,108,20543,63613,143796,37.92,6.25,32
21,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,109,176,1390,107,101251,237498,875000,37.05,6.25,18
22,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,96,78,1390,92,14726,41601,82310,37.05,6.25,32
23,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,81,80,1390,78,47151,94255,335500,40.39,6.25,23
24,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,111,87,1390,105,20398,60129,121056,37.92,6.25,26
25,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,69,130,1390,65,76356,132934,407373,34.73,6.25,19
26,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,78,76,1390,73,40121,77269,258313,38.02,6.25,25
27,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,90,81,1390,86,28168,70389,319092,37.05,6.25,28
28,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,116,79,1390,111,13822,45911,135094,37.33,6.25,28
29,CO48113,Dallas,Texas,TX,104,109,107,1030,74,24,...,115,84,1390,110,25368,78128,332500,37.05,6.25,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,89,121,3927,88,100902,169061,2200000,22.28,8.50,28
102,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,94,102,3927,92,72564,135147,1375000,22.28,8.50,27
103,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,95,146,3927,91,77960,145748,1301000,22.28,8.50,17
104,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,81,96,3927,79,63948,105357,1050000,22.28,8.50,26
105,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,96,70,3927,93,56088,106080,775000,22.28,8.50,26
106,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,104,119,3927,101,87059,165628,1550000,22.28,8.50,28
107,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,109,111,3927,105,65274,137154,1325000,22.28,8.50,28
108,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,144,123,3927,142,67464,170242,1450000,22.28,8.50,28
109,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,99,126,3927,96,85198,157733,1150000,22.28,8.50,24
110,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,116,107,3927,114,63662,139512,1550000,22.28,8.50,29
111,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,111,117,3927,109,65509,137434,1278870,22.28,8.50,29
112,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,159,174,3927,152,74870,220426,,22.28,8.50,28
113,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,128,98,3927,125,49666,124329,1250000,22.28,8.50,28
114,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,128,108,3927,125,44531,111720,1103000,19.77,8.50,33
115,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,172,80,3927,169,22507,81007,706000,22.28,8.50,33
116,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,145,107,3927,142,45800,128690,1086500,19.77,8.50,34
117,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,118,100,3927,116,47973,112912,1225000,19.77,8.50,33
118,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,177,96,3927,172,26136,93433,820000,22.28,8.50,31
119,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,130,112,3927,127,32190,88029,1012500,19.77,8.50,32
120,CO06075,San Francisco,California,CA,87,101,102,0,0,456,...,162,69,3927,158,21860,75279,640000,22.28,8.50,30
121,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,84,83,1149,86,23367,59147,,67.01,7.00,17
122,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,86,89,1149,88,20164,53539,,67.01,7.00,19
123,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,82,83,1149,85,19612,50045,,67.01,7.00,22
124,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,89,91,1149,90,22723,60201,,72.10,7.00,23
125,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,93,117,1149,94,30237,79328,,72.10,7.00,22
126,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,89,105,1066,90,25003,64836,162625,64.84,7.00,23
127,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,93,72,1149,94,23267,63758,,72.10,7.00,29
128,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,99,90,1149,100,24237,69057,,72.10,7.00,30
129,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,94,85,918,96,20264,55137,47500,64.46,7.00,36
130,CO28059,Jackson,Mississippi,MS,83,99,74,72,381,28,...,95,77,995,95,20786,57931,92000,65.69,7.00,37

In [2]:
#output the data set for analysis
outputfile = "resources/Full Data For Analysis.csv"
raw_all_reset.to_csv(outputfile)

NameError: name 'raw_all_reset' is not defined

In [3]:
#readin the data from .csv
inputfile = "resources/Full Data For Analysis.csv"
data_all=pd.read_csv(inputfile)
data_all.head()

,Unnamed: 0,geo_key,name,county name,state,state abbreviation,longitude,latitude,airportdist,airx,...,medsaleprice,ozone,pm10,precipann,rskcyhanx,rskcyhunx,rskcyquak,rskcyrisk,salestaxrate,trwave
0,0,ZI75390,Dallas,Dallas,Texas,TX,-96.840650,32.814164,2,0,...,NaN,0,0,37.05,0,0,0,0,6.25,53
1,1,ZI75251,Dallas,Dallas,Texas,TX,-96.771521,32.917204,7,0,...,221151.0,0,0,40.39,0,0,0,0,6.25,16
2,2,ZI75246,Dallas,Dallas,Texas,TX,-96.770643,32.795407,6,0,...,267187.0,0,0,37.05,0,0,0,0,6.25,30
3,3,ZI75202,Dallas,Dallas,Texas,TX,-96.803858,32.781909,5,0,...,201250.0,0,0,37.05,0,0,0,0,6.25,19
4,4,ZI75226,Dallas,Dallas,Texas,TX,-96.774934,32.786490,6,0,...,142500.0,0,0,37.05,0,0,0,0,6.25,28

In [4]:
data_all.describe()

,Unnamed: 0,longitude,latitude,airportdist,airx,ancestamer,ancestamind,ancestasian,ancesteuro,ancesthawai,...,medsaleprice,ozone,pm10,precipann,rskcyhanx,rskcyhunx,rskcyquak,rskcyrisk,salestaxrate,trwave
count,131.000000,131.000000,131.000000,131.000000,131.0,131.000000,131.000000,131.000000,131.000000,131.000000,...,1.190000e+02,131.0,131.0,131.000000,131.0,131.0,131.0,131.0,131.000000,131.000000
mean,65.000000,-101.461539,33.656169,11.290076,0.0,976.442748,98.305344,3577.961832,5312.587786,37.061069,...,4.357615e+05,0.0,0.0,36.939771,0.0,0.0,0.0,0.0,6.770992,26.961832
std,37.960506,10.936217,2.192579,5.929702,0.0,1030.180180,74.821417,6062.410696,4699.186972,107.893235,...,4.540472e+05,0.0,0.0,11.249619,0.0,0.0,0.0,0.0,0.906196,5.737065
min,0.000000,-122.490754,30.361710,1.000000,0.0,0.000000,0.000000,0.000000,3.000000,0.000000,...,3.826500e+04,0.0,0.0,19.770000,0.0,0.0,0.0,0.0,6.250000,16.000000
25%,32.500000,-97.005920,32.722150,7.000000,0.0,260.500000,42.000000,237.500000,1197.500000,5.000000,...,1.409450e+05,0.0,0.0,34.730000,0.0,0.0,0.0,0.0,6.250000,23.000000
50%,65.000000,-96.825709,32.842604,11.000000,0.0,669.000000,77.000000,1175.000000,4044.000000,11.000000,...,2.226250e+05,0.0,0.0,37.330000,0.0,0.0,0.0,0.0,6.250000,27.000000
75%,97.500000,-96.701902,32.984857,14.500000,0.0,1324.000000,141.500000,4024.500000,8400.500000,23.500000,...,5.135625e+05,0.0,0.0,38.690000,0.0,0.0,0.0,0.0,7.000000,31.000000
max,130.000000,-88.507256,37.824749,29.000000,0.0,5815.000000,377.000000,40705.000000,19731.000000,987.000000,...,2.200000e+06,0.0,0.0,72.100000,0.0,0.0,0.0,0.0,8.500000,53.000000

In [6]:
data_all.to_json("resources/alldata.JSON")

In [ ]:
data_all.to_sql("db/alldata.JSON")